// Generated by @nuxtjs/sitemap

declare module 'nitropack' {
  interface PrerenderRoute {
    _sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.2.9_h3@1.15.1_magicast@0.3.5_vite@6.2.2_@types+node@22.13.10_jiti@2.4_b2f6b1c1723db3b070602180ba2bd21f/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
    }
}

export {}
