// Generated by nuxt-seo-utils

declare module 'nitropack' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.4_magicast@0.3.5_rollup@4.35.0_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
     head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.4_magicast@0.3.5_rollup@4.35.0_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.4_magicast@0.3.5_rollup@4.35.0_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
    head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.4_magicast@0.3.5_rollup@4.35.0_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
}

declare module '@nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.4_magicast@0.3.5_rollup@4.35.0_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

declare module 'nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.4_magicast@0.3.5_rollup@4.35.0_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

export {}
