// Generated by nuxt-schema-org

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@5.0.4_magicast@0.3.5_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}
declare module '#app' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@5.0.4_magicast@0.3.5_vue@3.5.13_typescript@5.8.2_/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}

export {}
