name: AI Auto Blog Generator

on:
  schedule:
    # Run twice daily: 9 AM and 9 PM UTC (4 PM and 4 AM Vietnam time)
    - cron: '0 9,21 * * *'
  workflow_dispatch: # Allow manual trigger
    inputs:
      force_generate:
        description: 'Force generate even if post exists'
        required: false
        default: 'false'
        type: boolean

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.6.2

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Generate AI blog post
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: node scripts/ai-auto-blog.js

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "AI Blog Generator"
        git add content/posts/

        # Count new posts
        NEW_POSTS=$(git diff --cached --name-only | wc -l)

        git commit -m "🤖 AI Blog Batch: ${NEW_POSTS} new posts - $(date +'%Y-%m-%d %H:%M')"
        git push

    - name: Build for GitHub Pages
      if: steps.verify-changed-files.outputs.changed == 'true'
      env:
        BASE_URL: /${{ github.event.repository.name }}/
        NUXT_CONFIG_FILE: nuxt.config.static.ts
      run: |
        pnpm generate

    - name: Deploy to GitHub Pages
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: ${{ secrets.CUSTOM_DOMAIN }} # Optional: if you have custom domain

    - name: Notify on success
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        echo "✅ New blog post generated and deployed successfully!"
        echo "📅 Date: $(date)"
        echo "🔗 Check your blog for the new post"

    - name: Notify on no changes
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: |
        echo "ℹ️ No new blog post generated (may already exist for today)"
