name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install
      - run: pnpm run generate

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r .output/public/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
